
package co.com.codesoftware.server;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SAFWSService", targetNamespace = "http://server.codesoftware.com.co/", wsdlLocation = "http://169.254.79.173:9999/WS/server/SAFWS?wsdl")
public class SAFWSService
    extends Service
{

    private final static URL SAFWSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(co.com.codesoftware.server.SAFWSService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = co.com.codesoftware.server.SAFWSService.class.getResource(".");
            url = new URL(baseUrl, "http://169.254.79.173:9999/WS/server/SAFWS?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://169.254.79.173:9999/WS/server/SAFWS?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SAFWSSERVICE_WSDL_LOCATION = url;
    }

    public SAFWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SAFWSService() {
        super(SAFWSSERVICE_WSDL_LOCATION, new QName("http://server.codesoftware.com.co/", "SAFWSService"));
    }

    /**
     * 
     * @return
     *     returns SAFWS
     */
    @WebEndpoint(name = "SAFWSPort")
    public SAFWS getSAFWSPort() {
        return super.getPort(new QName("http://server.codesoftware.com.co/", "SAFWSPort"), SAFWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SAFWS
     */
    @WebEndpoint(name = "SAFWSPort")
    public SAFWS getSAFWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.codesoftware.com.co/", "SAFWSPort"), SAFWS.class, features);
    }

}
